### ISSUE TITLE
Error when using multiple configs files from different folders

### ISSUE THREAD

**Issue by hchouaib** [rochacbruno/dynaconf#94] opened 2018-10-17 15:35 UTC
Hi Bruno, 
I am trying to load configuration from multiple files in different folders
This is the folder structure that i use:
my_project
├── config1
│   ├── __init__.py
│   └── settings.toml
├── config2
│   ├── __init__.py
│   └── settings.toml
└── main.py
in each settings.toml i have 2 environment **development** and **production** ad **VAR1** for config1 and **VAR2** for config2
```
[development]
VAR1 = 'var1_dev'
[production]
VAR1 = 'var1_prod'
```
In the main 
```
import os
from dynaconf import settings

from my_project.config1 import __file__ as config1_file
from my_project.config2 import __file__ as config2_file

f1 = os.path.join(os.path.dirname(config1_file), 'settings.toml')
f2 = os.path.join(os.path.dirname(config2_file), 'settings.toml')

os.environ['SETTINGS_MODULE_FOR_DYNACONF'] = "{},{}".format(f1, f2)
                                                        
print('development')
print(settings.VAR1)
print(settings.VAR2)

print('production')
settings.setenv('production')
print(settings.VAR1)
print(settings.VAR2)
```
For default and development it works but when i try to setenv to production i have this error :
```
development
var1_dev
var2_dev

production
Traceback (most recent call last):
  File "/home/hch/PycharmProjects/dynaconf/iia/my_project/main.py", line 13, in <module>
    settings.setenv('production')
  File "/home/hch/.virtualenvs/dynaconf/lib/python3.6/site-packages/dynaconf/base.py", line 459, in setenv
    self.execute_loaders(env=env, silent=silent, filename=filename)
  File "/home/hch/.virtualenvs/dynaconf/lib/python3.6/site-packages/dynaconf/base.py", line 572, in execute_loaders
    filename=filename)
  File "/home/hch/.virtualenvs/dynaconf/lib/python3.6/site-packages/dynaconf/loaders/__init__.py", line 53, in settings_loader
    settings_module = settings_module or obj.settings_module
  File "/home/hch/.virtualenvs/dynaconf/lib/python3.6/site-packages/dynaconf/base.py", line 413, in settings_module
    if settings_module != self.SETTINGS_MODULE:
AttributeError: 'Settings' object has no attribute 'SETTINGS_MODULE'
```

**Comment by rochacbruno** [comment] 2018-10-19 17:01
@hchouaib confirmed this is a bug, thanks for reporting

this is a problem in `setenv` I am working on it.

```
python app.py
development
var1_dev
var2_dev
production
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    settings.setenv('production')
  File "/home/rochacbruno/Projects/python/dynaconf/dynaconf/base.py", line 487, in setenv
    self.execute_loaders(env=env, silent=silent, filename=filename)
  File "/home/rochacbruno/Projects/python/dynaconf/dynaconf/base.py", line 605, in execute_loaders
    filename=filename)
  File "/home/rochacbruno/Projects/python/dynaconf/dynaconf/loaders/__init__.py", line 53, in settings_loader
    settings_module = settings_module or obj.settings_module
  File "/home/rochacbruno/Projects/python/dynaconf/dynaconf/base.py", line 441, in settings_module
    if settings_module != self.SETTINGS_MODULE:
AttributeError: 'Settings' object has no attribute 'SETTINGS_MODULE'

```

**Comment by rochacbruno** [comment] 2018-10-19 17:05
The workaround is 
```
DYNACONF_SETTINGS="config_1/settings.toml,config_2/settings.toml"
```

or

```
os.environ['DYNACONF_SETTINGS'] = "{},{}".format(f1, f2)
```


```bash
$ python app.py
development
var1_dev
var2_dev
production
var1_prod
var2_prod

```

the problem is when `SETTINGS_MODULE_FOR_DYNACONF` is replaced

**Comment by rochacbruno** [comment] 2018-10-19 18:30
Fixed in #97

**Closed** 2018-10-19 18:48 UTC
Labels: bug

**Comment by hchouaib** [comment] 2018-10-21 02:33
Thank you @rochacbruno

**Comment by brucegibbins** [comment] 2018-10-22 10:19
Hi. Realise this modification was for v1.07 and I am using v1.06 but I get the same error when there is only one settings file and no merge happening. I used your v1.07 sample 'multiple file' as a base for my test as the end goal for me was to have the settings file inside a folder rather than at the same level as the main application. I have attached a screenshot of the error and the values in .env, app.py and settings.toml

I am not sure if I am missing something. Should this work already in v1.06 given that no merge is occurring

So, the folder structure is
\dyna_example
|-----.env
|-----app.py
|-----config_1
|-------\settings.toml

![dyna_conf](https://user-images.githubusercontent.com/16873240/47288013-8ce28180-d637-11e8-8bf7-c2ae4776d6ba.png)

cheers

**Comment by rochacbruno** [comment] 2018-10-22 21:40
@brucegibbins The fix is not released yet, Planning a release to the end of this week.

To get the version with the fix do `pip install https://github.com/rochacbruno/dynaconf/tarball/master`

**Comment by Krausso** [comment] 2020-12-21 20:04
![image](https://user-images.githubusercontent.com/52201020/102817484-8814e600-43d8-11eb-90e7-40ff22102cd2.png)

**Comment by Krausso** [comment] 2020-12-21 20:05
Just copied an example from dynaconf.com, kinda weird
