### ISSUE TITLE
DATABASES setting for Django not being set

### ISSUE THREAD

**Issue by dkliban** [rochacbruno/dynaconf#89] opened 2018-09-28 20:15 UTC
dynaconf is properly showing the settings I put into /etc/pulp/settings.py

```
(pulp) [vagrant@pulp3 pulp]$ dynaconf list -k DATABASES
Django app detected
Working in development environment 
DATABASES: {'default': {'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.dummy',
             'HOST': 'postgres',
             'NAME': 'pulp',
             'PORT': '5432',
             'USER': 'pulp'}}
```
However, django is not using the setting. It seems like Django is loading the settings for the database before dynaconf is loaded.

**Comment by rochacbruno** [comment] 2018-09-28 20:43
Looks like Django is accessing `DATABASES` before the load of `INSTALLED_APPS` so I can think in a way to fix it.

Load dynaconf explicitly in `manage,py` in `wsgi.py` 

after this line.
https://github.com/rochacbruno/dynaconf/blob/master/example/django_example/manage.py#L6

**Comment by rochacbruno** [comment] 2018-09-28 21:07
I want to add an implementation targetting Python 3.7 using this https://www.python.org/dev/peps/pep-0562/

and also I am going to try other solutions.

If we figureout that the proper way is calling dynaconf on `manage.py` and `wsgi.py` then I'll add this to the docs.

**Comment by dkliban** [comment] 2018-09-28 21:11
Thank you! I was able to follow your advice here[0].

[0] https://github.com/pulp/pulp/pull/3678/files

**Comment by mspinelli** [comment] 2018-11-14 15:22
Any progress on this problem?

> I want to hear more opinions about this idea ^.

I take it the dual environment variable export won't work as is right now? I haven't tried it yet. But I do like this idea better than the alternatives.

That said I am on Python 3.7. What does the module.__getattr__ method look like to solve this problem?

**Comment by rochacbruno** [comment] 2018-11-14 21:52
@mspinelli the proposed solution is not implemented yet, it needs to be implemented.

Right now to use django there are 2 solutions

- 1) Load dynaconf in `INSTALLED_APPS` knowing that DATABASE should be kept on django's settings.
- 2) Load dynaconf in all the entry points as `manage.py`, `wsgi.py` and others.

**Comment by dmsimard** [comment] 2018-12-21 15:43
Hi o/

By the way, I think @apollo13 had a good idea by getting dynaconf to load settings from within settings instead of patching entrypoints for this issue.

You can see the commit here: https://github.com/openstack/ara-server/commit/fdcc003fd9c9c05f1e0fcbaa502939f592503e79

**Comment by apollo13** [comment] 2018-12-29 21:54
@rochacbruno Against what? My changes just use dynaconf directly and drop the Django integration. There is not really anything to patch with that regard in dynaconf itself…

**Comment by jasisz** [comment] 2019-02-19 10:36
I've found two more Django corner-cases.
One is `ALLOWED_HOSTS` - even if you change it with dynaconf, it still will have default value.
The other case is when you use `settings.SOME_CONFIG` in your templates - in such scenario dynaconf fails with `'Settings' object has no attribute '__name__'` - this is because it pases through the `django.templates.base._resolve_lookup` which inspects with getcallargs on `LazySettings` and it fails.

**Comment by rochacbruno** [comment] 2019-02-19 14:47
The template problem must e resolved with the recommendation to use `['key`]` syntax.

The other problems there is a way to fix using getattr but only for python 3.7+

**Comment by rochacbruno** [comment] 2019-03-27 13:54
IN progress on #126

**Comment by rochacbruno** [comment] 2019-04-09 02:00
2.0.0 released DATABASE stuff is now fixed.
read more in https://dynaconf.readthedocs.io/en/latest/guides/django.html
example in https://github.com/rochacbruno/dynaconf/tree/master/example/django_example

@jasisz can you please test the render template? or add a reproducer on the https://github.com/rochacbruno/dynaconf/tree/master/example/django_example

Thanks!

**Closed by rochacbruno** 2019-04-09 02:00 UTC
Labels: Pending Release, enhancement
