### ISSUE TITLE
[RFC] Locked / read-only settings

### ISSUE THREAD

**Issue by JGMEYER** [rochacbruno/dynaconf#297] opened 2020-02-15 01:40 UTC
**Is your feature request related to a problem? Please describe.**
In my current project, there are some settings that are intended only for the initialization of the app and could cause problems if modified and re-read midway through its execution, i.e. the main loop.

It would be useful if we could flag a setting as read-only, which would then explicitly error on calls to `settings.set()` or `settings.update()` on the setting.

The primary intention of this feature is to prevent other developers on a project from mistakenly modifying values that could introduce bugs if modified during a program's execution. This can help catch the issue prior to a manual code review and would be less error-prone.

**Describe the solution you'd like**
As I'm new to dynaconf, I don't have an idiomatic solution to present for this Issue. However, I imagine an explicit `readonly` setting that can be added in the .toml, and optionally, the .py levels would be clear and concise to describe this behavior.

**Describe alternatives you've considered**
There are currently ways to extend dynaconf functionality or to monkey-patch these features into the existing module, but this Issue focuses solely on a native configuration that would provide this functionality through dynaconf source.

There are also ways to structure code to read in these "readonly" values once and lock them behind a setter/getter where they are read. However, this still does not guarantee these values will not be used elsewhere and the intention is not easily or immediately visible to other developers contributing to the source.

**Additional context**
I can respond to additional questions in this Issue if it needs additional clarification.

**Comment by rochacbruno** [comment] 2020-09-12 04:12
This is a duplicate of #247 I will keep only that one opened but the work will cover also this issue

**Closed by rochacbruno** 2020-09-12 04:12 UTC
Labels: Not a Bug, RFC
