### ISSUE TITLE
Duplicated (non-default) list entries when using environments and merge enabled

### ISSUE THREAD

**Issue by poel22** [rochacbruno/dynaconf#653] opened 2021-09-07 08:58 UTC
First and foremost: **Thank you** for this project

I stumbled over an issue with environments and the merge of lists, namely non-default list items are duplicated in final (environment-specific) list.

### Steps to reproduce

python==3.9.6
dynaconf==3.1.5

**config file:**
`/some_folder/test_settings.yaml`
```yaml
default:
  SOME_KEY: "value"
  SOME_LIST:
    - "item_1"
    - "item_2"
    - "item_3"
other:
  SOME_KEY: "new_value"
  SOME_LIST:
    - "item_4"
    - "item_5"
```

**test file:**
`/some_folder/test.py`
```python
from dynaconf import Dynaconf

settings = Dynaconf(settings_files=["test_settings.yaml"], environments=True, merge_enabled=True)

print(f'default env: {settings.from_env("default").SOME_LIST}')
print(f'other env: {settings.from_env("other").SOME_LIST}')
```

**results in:**
```
default env: ['item_1', 'item_2', 'item_3']
other env: ['item_1', 'item_2', 'item_3', 'item_4', 'item_5', 'item_4', 'item_5']
```

**expected:**
```
default env: ['item_1', 'item_2', 'item_3']
other env: ['item_1', 'item_2', 'item_3', 'item_4', 'item_5']
```

**Comment by andressadotpy** [comment] 2021-09-22 20:18
I believe the problem is inside `object_merge()` function and can be solved by adding an elif statement to check if item is already in new and if it is, a continue. Something like this:

```python3
    if isinstance(old, list) and isinstance(new, list):
        for item in old[::-1]:
            if unique and item in new:
                continue
            elif item in new:
                continue
            new.insert(0, item)
```

But with that change, I had to change one test that used unique in `test_utils.py`: 

```python3
def test_merge_existing_list():
    existing = ["bruno", "karla"]
    object_merge(existing, existing)
    # calling twice the same object does not duplicate
    assert existing == ["bruno", "karla"]

    new = ["erik", "bruno"]
    object_merge(existing, new)
    assert new == ["karla", "erik", "bruno"]
```

Does that makes sense?

**Comment by rochacbruno** [comment] 2021-09-22 21:19
@andressadotpy

What about something like this real example of an application that sets the transform pipeline of a request middleware.

```py

MIDDLEWARE_PIPELINE = [
    "module.sanitize", 
    "module.strip_whitespaces",
    "module.parse_markdown",
]

```

Those are function paths that takes the request body and transforms, the end result is `parse_markdown(strip_whitespaces(sanitize(request)))`

But on that application there is a specific user that wants to also add `module.sanitize` to the end of the pipeline, to run twice (parse_markdown can add some unsafe tags).

User customizes using

```py
export DYNACONF_MIDDLEWARE_PIPELINE = "@merge module.sanitize"
```

or using another `settings.toml` provided on the plugin

```toml
[production]
dynaconf_merge = true
MIDDLEWARE_PIPELINE = ["module.sanitize"]
```

The expected result is:

```py
MIDDLEWARE_PIPELINE = [
    "module.sanitize", 
    "module.strip_whitespaces",
    "module.parse_markdown",
	"module.sanitize",
]
```

I don't know what to do in that case, as this is something we have users relying on it.

IIRC that is why we added the `dynaconf_merge_unique` marker. https://www.dynaconf.com/merging/#avoiding-duplications-on-lists 

I was thinking about other strategies discussed here https://github.com/rochacbruno/dynaconf/issues/299#issuecomment-892135400 

I would love to hear what do you think about those ideas @andressadotpy :) 

Thanks

**Comment by andressadotpy** [comment] 2021-09-23 14:44
@exageraldo and I were investigating the code and we noticed that [_merge_before_set()](https://github.com/andressadotpy/dynaconf/blob/02cbf0562107b293461ec1aef8892c9afec8c6c0/dynaconf/base.py#L903) method is being called recursively many times, but we believe that the **last** time shouldn't happen and needs a way to validate better this situation. What are your thoughts on that?

Adding a few `prints()` to identify the problem:

```python
def _merge_before_set(self, existing, value):
        """Merge the new value being set with the existing value before set"""
        global_merge = getattr(self, "MERGE_ENABLED_FOR_DYNACONF", False)
        print('Calling _merge_before_set')
        print('Existing value: ', existing)
        print('New value: ', value)
        ...
        return value
 ```
 the output is:
 ```
 Calling _merge_before_set
Existing value:  []
New value:  test_settings.yaml
Calling _merge_before_set
Existing value:  []
New value:  test_settings.yaml
Calling _merge_before_set
Existing value:  []
New value:  test_settings.yaml
Calling _merge_before_set
Existing value:  value
New value:  new_value
Calling _merge_before_set
Existing value:  ['item_1', 'item_2', 'item_3']
New value:  ['item_4', 'item_5']
Calling _merge_before_set
Existing value:  ['item_1', 'item_2', 'item_3', 'item_4', 'item_5']
New value:  ['item_4', 'item_5']
 ```
 
 That way, the [object_merge()](https://github.com/andressadotpy/dynaconf/blob/02cbf0562107b293461ec1aef8892c9afec8c6c0/dynaconf/utils/__init__.py#L36) function is called twice and in the second time as if the existing (old) value was `['item_1', 'item_2', 'item_3', 'item_4', 'item_5']`  and a new value to be added as `['item_4', 'item_5']`, duplicating the value of the merged list. Does that makes sense?
 
 We tried to find were those calls are being made but we couldn't. Do someone can help us out?

**Comment by andressadotpy** [comment] 2021-09-23 14:46
@rochacbruno those things you mentioned are part of the things we discussed above? Sorry, I didn't understand it very well

**Comment by rochacbruno** [comment] 2021-09-23 15:58
@andressadotpy yes, a simpler example is also listed on https://www.dynaconf.com/merging/#avoiding-duplications-on-lists

given existing setting is

```py
In [1]: from dynaconf import Dynaconf

In [2]: settings = Dynaconf(
   ...:   SCRIPTS=["1.sh", "2.sh", "3.sh"]
   ...: )

In [3]: settings.scripts
Out[3]: <BoxList: ['1.sh', '2.sh', '3.sh']>
```

Now assume the user wants to add `['3.sh', '4.sh']` to the list and get no duplications

```py
In [4]: settings.set("SCRIPTS", ["3.sh", "4.sh", "dynaconf_merge_unique"])

In [5]: settings.scripts
Out[5]: <BoxList: ['1.sh', '2.sh', '3.sh', '4.sh']>
```

But, there is **another case** when the user really wants to duplicate, for example, add `"1.sh"` again at the end.

```py
In [6]: settings.set("SCRIPTS", "@merge 1.sh")

In [7]: settings.scripts
Out[7]: <BoxList: ['1.sh', '2.sh', '3.sh', '4.sh', '1.sh']>
```

**The Problem** is that, wherever the data comes from:

- environment variables
- settings files in multiple envs `default, other, etc`
- settings.set calls

The same **object_merge** function is called, and looks like we need a different behavior for this issue specific case.

The problem described here can be solved if the settings file is

```yaml
default:
  SOME_KEY: "value"
  SOME_LIST:
    - "item_1"
    - "item_2"
    - "item_3"
other:
  SOME_KEY: "new_value"
  SOME_LIST:
    - "dynaconf_merge_unique"
    - "item_4"
    - "item_5"
```

Notice: "dynaconf_merge_unique" as part of the list.

We maybe need to implicit add that mark on a list, if the key exist in an environment called `default`

**Comment by andressadotpy** [comment] 2021-09-24 18:15
To solve this issue based in this discussion I thought about a small change inside `dynaconf/base.py` adding to the `Settings` class a method to check if inside the settings file already exists an environment called `default`.

```python3
        ...
        def is_key_from_default_env(self):
        try:
            with open(self.settings_file, "r") as file:
                settings = yaml.full_load(file)
                if settings.get("default"):
                    return True
        except Exception: 
            return False
        ...
```
I don't like the `except Exception` very much, but as I wanted to check only if inside a settings file there's a `default` environment and this method isn't called only when there's a file I thought about doing like this. What do you think?

This validation is called inside the method [_merge_before_set()](https://github.com/andressadotpy/dynaconf/blob/02cbf0562107b293461ec1aef8892c9afec8c6c0/dynaconf/base.py#L905):

```python3
        ...
        
        if isinstance(value, (list, tuple)):
            local_merge = (
                "dynaconf_merge" in value or "dynaconf_merge_unique" in value
            )
            default_env = self.is_key_from_default_env()  # Here is the validation
            if global_merge or local_merge:
                value = list(value)
                unique = True if default_env else False   # This is changed
                if local_merge:
                    try:
                        value.remove("dynaconf_merge")
                    except ValueError:  # EAFP
                        value.remove("dynaconf_merge_unique")
                        unique = True
                value = object_merge(existing, value, unique=unique)
        ...
```
All tests passed with those changes, including the test I added with this problem. What do you think about those changes?

**Closed** 2021-10-04 18:01 UTC
Labels: bug
